// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	chassis "github.com/steady-bytes/draft/pkg/chassis"

	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// RegisterRPC provides a mock function with given fields: server
func (_m *Handler) RegisterRPC(server chassis.Rpcer) {
	_m.Called(server)
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
